const express = require("express");
const path = require("path");
const axios = require("axios");
const routes = require("./routes");
const app = express();

/**
 * Content of the public folder will be generated by Webpack
 */
const DIST = path.join(__dirname, "../../dist");
app.use(express.static(DIST));

/**
 * Axios handler for timeouts
 * Will trigger the regular error handler
 */
axios.interceptors.response.use(
  config => config,
  error => {
    error.code = 408;
    return Promise.reject(error);
  }
);

/**
 * Access-Control-Allow-Origin to *
 */
app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  next();
});

// Add routes
app.use("/api", routes);

/**
 * Redirect the rest to the Vue app
 * index.html needs to be generated by Webpack
 */
app.use((req, res) => {
  res.sendFile(`${DIST}/index.html`);
});

/**
 * Custom JSON error handler
 */
// eslint-disable-next-line
app.use((err, req, res, next) => {
  // eslint-disable-next-line
  console.error(err.stack);
  /**
   * Using err.response when the error is caused by speedrun.com
   * Using err.code when the error is caused by our own api or twitch api
   */
  const status = err.response ? err.response.status || 500 : err.code || 500;
  const statusText = err.response ? err.response.statusText || "" : "";
  const message = err.message || "";
  res.status(status).json({
    status,
    statusText,
    message
  });
});

module.exports = app;
