name: deploy_dev

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        PATH: "/tmp/speedsouls/"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        envs: PATH
        script: |
          git clone https://github.com/CapitaineToinon/buefy-souls.git $PATH
          cd $PATH
          pwd
