name: deploy_prod

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: Build and deploy to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'master'

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
    
      - name: Build Project
        run: |
          yarn install
          VUE_APP_GITHUB_SHA=$GITHUB_SHA \
          VUE_APP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
          VUE_APP_GITHUB_SERVER_URL=$GITHUB_SERVER_URL \
          yarn build

      - name: List output files
        run: ls dist

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.PROD_HOST }}
          FTP_USERNAME: ${{ secrets.PROD_USERNAME }}
          FTP_PASSWORD: ${{ secrets.PROD_PASSWORD }}
          METHOD: sftp
          LOCAL_DIR: dist
          REMOTE_DIR: /tmp/SpeedSouls
          ARGS: --delete

      - name: Move final files 
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rm -r ~/SpeedSouls/* && mv /tmp/SpeedSouls/* ~/SpeedSouls/ && rm -r /tmp/SpeedSouls/
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}

