name: deploy_dev

on:
  push:
    branches:
      - dev

jobs:
  FTP-Deploy-Action:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'dev'

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Project
        run: |
          yarn install
          VUE_APP_GITHUB_SHA=$GITHUB_SHA \
          VUE_APP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
          VUE_APP_GITHUB_SERVER_URL=$GITHUB_SERVER_URL \
          yarn build

      - name: List output files
        run: ls dist

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: dist/
          server-dir: /tmp/SpeedSouls/

      - name: Move final files
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: shopt -s dotglob && rm -r ~/SpeedSouls/* && mv /tmp/SpeedSouls/* ~/SpeedSouls/ && rm -r /tmp/SpeedSouls/ && shopt -u dotglob
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
