name: deploy_dev

on:
  push:
    branches:
      - dev

jobs:
  FTP-Deploy-Action:
    name: Build and deploy beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Build Project
        run: |
          yarn install
          VUE_APP_GITHUB_SHA=$GITHUB_SHA \
          VUE_APP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
          VUE_APP_GITHUB_SERVER_URL=$GITHUB_SERVER_URL \
          yarn build

      - name: List output files
        run: ls dist

      - name: Enable maintenance mode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: touch ~/SpeedSouls/maintenance.enable
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: sftp://${{ secrets.DEV_HOST }}/SpeedSouls/
          ftp-username: ${{ secrets.DEV_USERNAME }}
          ftp-password: ${{ secrets.DEV_PASSWORD }}
          local-dir: dist

      - name: Disable maintenance mode
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: rm ~/SpeedSouls/maintenance.enable
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
