name: deploy_dev
on:
  push:
    branches: 
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      TMP_PATH: /tmp/speedsouls
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        envs: GITHUB_REPOSITORY
        script: echo "$GITHUB_REPOSITORY"
