name: deploy_dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-to-dev-env:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'dev'

      # Read node version from `.nvmrc` file
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - uses: actions/setup-node@v2
        with:
          # use the output from the action
          node-version: "${{ steps.nvmrc.outputs.NVMRC }}"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build Project
        run: |
          yarn install
          VUE_APP_GITHUB_SHA=$GITHUB_SHA \
          VUE_APP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
          VUE_APP_GITHUB_SERVER_URL=$GITHUB_SERVER_URL \
          yarn build

      - name: List output files
        run: ls dist

      - name: SCP content to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          port: 22
          source: "dist/*, dist/.htaccess"
          target: "/tmp/SpeedSouls/"

      - name: Move final files
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            shopt -s dotglob && \
            rm -r ~/SpeedSouls/* && \
            mv /tmp/SpeedSouls/* ~/SpeedSouls/ && \
            rm -r /tmp/SpeedSouls/ && \
            find ~/SpeedSouls/ -type f -exec chmod 644 -- {} + && \
            shopt -u dotglob
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
